version: '3.9'
services:
  backend:
    build: ./backend
    container_name: books-backend
    ports:
      - "8080:8080"
  db:
    image: mongo
    container_name: books-db
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
